minimumReleaseAge: 10080 # Only install package versions that have been published for at least 7 days.
minimumReleaseAgeStrict: true
allowBuilds:
  keccak: true
  node-hid: true
  secp256k1: true
  usb: true
